### ISSUE TITLE
Requesting .locationAlwaysAndWhenInUse when "whenInUse" is already accepted calls "didDenied" directly

### ISSUE THREAD

**Issue by KevinQuisquater** [ivanvorobei/SPPermissions#119]
Steps to reproduce:

- Before showing SPPermission Dialog, call `locationManager.requestWhenInUseAuthorization()`. In the app, tap `Allow`.
- Call SPPermissionDialog with .locationAlwaysAndWhenInUse

```
SPPermission.Dialog.request(with: [.locationAlwaysAndWhenInUse],
                            on: self,
                            delegate: self,
                            dataSource: self)
```

- When you tap `ALLOW`, the permission alert to access "Always On" location appears for a split second but is immediately closed, because SPPermission seems to call `didDenied(permission:)` and shows the alert that shows that the Permission was denied, with the `Cancel` and `Settings` option button.

**Comment by ivanvorobei** [comment]
@KevinQuisquater I am publish new version 5.0.2, if bug show now - please, write here.
