### ISSUE TITLE
Changeable font and size texts

### ISSUE THREAD

**Issue by emaddoma** [ivanvorobei/SPPermissions#133]
Hello, 

First: The library is pretty good and I appreciate the time you've put into it.

With that being said, there have been changes since the first time I used it and I wish some of the features hadn't been deprecated and I also have some suggestions...

1. headerBackgroundView used to be customizable.  Really missing this.
2. The layout of each item in the dialog cuts off the item's descriptive text.  Consider a layout that would allow at least three times as much text.  At this time I'm limited to about 34 characters, which isn't adequate.  Each item could be of a variable height and the height of the custom text could define the height of each.
3. The icon for each item in the dialog should be optional (allow for no icon at all)
4. The fonts for the title and subtitle of the modal are too large and should be customizable (color and size)

**Comment by ivanvorobei** [comment]
Hi! Thanks for feedback! 
Soon I start recreate lib for clean code and new design. I am attach it and added in new version. 
Thanks.

**Comment by ivanvorobei** [comment]
@emaddoma I am publish new version `5.0`, now all views public. You can configure it. 
Also text in permissions cell not cuts!
