### ISSUE TITLE
[Request] Bluetooth Permission for iOS 13

### ISSUE THREAD

**Issue by ankitatdelhii** [ivanvorobei/SPPermissions#134]
Hello,

First of all, I would like to say **thanks** for creating such an amazing library.
With iOS 13, now we need to ask for Bluetooth permissions explicitly from the user as well. It would be great if you could make a dialogue box of SPPermssion for it.

Thanks

**Comment by ivanvorobei** [comment]
Good day! I will add it in new version of SPPermission.

**Comment by ivanvorobei** [comment]
@ankitatdelhii good day!
You can add here code of request and check state permission?

**Comment by multinerd** [comment]
https://stackoverflow.com/a/58261624/5434784

**Comment by nab0y4enko** [comment]
@ivanvorobei I also want to thank you for your wonderful library.
Tell me pls if there is any work on adding with Bluetooth permissions

**Comment by ivanvorobei** [comment]
@nab0y4enko I am try adding it in current week.

**Comment by ivanvorobei** [comment]
I am added `bluetooth` in `5.2.6` version. 

In this version you can't request `bluetooth`, but can check it state. If you know how request bluetooth permission, please, create pull request or send me code.

Icon added. Need only code for request permission.

**Comment by dlackty** [comment]
#198 seems like a good way for requesting bluetooth permission.

**Comment by ivanvorobei** [comment]
Complete in new version
