### ISSUE TITLE
5.0.2 -> 4.1.4 Compatibility 

### ISSUE THREAD

**Issue by jminutaglio** [ivanvorobei/SPPermissions#142]
Hello,

First, Thank you for such an excellent project.

A question: upon upgrade to 5.0.2 from a 4.1.4 based project I receive a number of compile errors.  Is 5.0.2 designed to be backwards compatible with 4.1.4 syntax and functionality?

Thank you!
-J

**Comment by ivanvorobei** [comment]
Good day! 
If you need 4.1.4 version, you can install this version. It simple. 

In 5.0 versions I do syntax more simple, I recommend you do small changes in your code. See Readme with examples usage, so simple)

Thanks for feedback!
