### ISSUE TITLE
Great Job on the new changes!!! I have a couple questions.

### ISSUE THREAD

**Issue by sdevo619** [ivanvorobei/SPPermissions#143]
Do you have an example of how the new 
func data(for permission: SPPermission) -> SPPermissionData? is supposed to be setup, as it it won't let me create a SPPermissionData object.

<img width="1730" alt="image" src="https://user-images.githubusercontent.com/7008354/69100824-e7a10500-0a12-11ea-9488-641dbd68f2de.png">

I was using the old functions to do this before:
func image(for permission: SPPermission) -> UIImage? {
func description(for permission: SPPermission) -> String? {

I am trying to see what I need to do to support custom icons and descriptions again, with the newest changes you just made. Keep up the great work and thank you again for keep this up to date and working great!!!

**Comment by ivanvorobei** [comment]
Good day! You do correct.
It my mistake, sorry. 

I am upload new version `5.0.4` with fix it. If you install via `Cocoapods`, now need some delay for refresh repo (`Cocoapods start use CDN with cache`).

**Comment by sdevo619** [comment]
Thank your for fixing that so quickly!!!! The newest build fixed that issue for me. I found another bug in the process though. Every time I relaunch the app in the simulator the permission order changes. One launch the order is Media Library, Notification, then Location. Then terminate the app, and relaunch, and the order will be different the next launch. It will be Media Library, Location, then Notification. Probably just need to set the order on the array you use to hold them. Thank you again!!! Keep up the great work!!!!

**Comment by ivanvorobei** [comment]
@sdevo619 thanks, true, order shuffle. 
I fix it now, no problem) 
Thanks for feedback
