### ISSUE TITLE
[Request] After user denied permissions, can we don't go to the settings?

### ISSUE THREAD

**Issue by ppavel22** [ivanvorobei/SPPermissions#145]
Hi Ivan, and thanks a lot for your work.
After user denied permission, can we don't go to the settings for the first time when we denied permission?

Thanks

**Comment by ivanvorobei** [comment]
Hi! 
Yes, I am added it in 1-2 hours. I am forget about this in new version. I will close issue when public new version. 

Thanks for feedback.

**Comment by ivanvorobei** [comment]
I am publish new version 5.0.5. How customise alert, see section [DataSource & Delegate](https://github.com/ivanvorobei/SPPermissions#datasource--delegate).
