### ISSUE TITLE
[Issue] 5.0.5 issue

### ISSUE THREAD

**Issue by ppavel22** [ivanvorobei/SPPermissions#146]
Hi Ivan, and thanks a lot for your work.
You have been updated to 5.0.5 but we can't do notificationData.showAlertOpenSettingsWhenPermissionDenied = false, because is inaccessible due to 'internal' protection level. 
And I have small request, can you add Bluetooth Permission for iOS 13?

Thanks a lot

**Comment by ivanvorobei** [comment]
Yes, true. I publish `5.0.6`. 
Sorry for this. 

Yes, I am soon add `Bluetooth`, maybe tomorrow.

**Comment by ivanvorobei** [comment]
About `Bluetooth`, you can check it in #134 issue
