### ISSUE TITLE
One more question on the new updates

### ISSUE THREAD

**Issue by sdevo619** [ivanvorobei/SPPermissions#147]
What did you replace the didHide() method with??? I am using the dialog prompt, just FYI. Thank you again. Keep up the great work!!!!

**Comment by ivanvorobei** [comment]
I remove it. You use it method?

**Comment by sdevo619** [comment]
Yes, if someone dismisses the prompt, and the functionality is required to use the app, or maybe they don't want to use all of the features and don't allow access to one of the permissions, it allows me to re-present it, if that permission is absolutely necessary, before they move to the next view controller, or push to the next view controller if the permission is not required, and it also keep them from moving past it, and attempting to use the app and potentially have a bunch of stuff crashing. I use it in both the apps Im using SPPermissions in, so I need to know when permission VC is dismissed. Does this make sense???

**Comment by ivanvorobei** [comment]
Yes, I agree with you. I add it now.

**Comment by sdevo619** [comment]
Thank you very much!!!! I appreciate that very much!!!! I will let you know if I find anything else. One thing you may want to also add to your docs on this too, is how to force Dark or Light Theme on the prompt. I know most devs who work with iOS 13 probably know by now, but it took me a minute to figure out where to add it, and will keep you from having to answer it. My app is dark theme all the time, so the white prompt just didn't look right, but the dark theme looks great!!!!

controller.overrideUserInterfaceStyle = .dark

**Comment by ivanvorobei** [comment]
@sdevo619 I am upload new version `5.0.7`, now fix order permissions and add `didHide` to delegate. 

`overrideUserInterfaceStyle` is controller property, like `viewDidLayoutSubview` and other. No need add it docs, because it basic. It new, of course, but it basic. You can call it for any controller) 

Thanks again for feedback!

**Comment by sdevo619** [comment]
I just updated my cocoa pods install and saw you readded the didHide method Thank you very much!!!! I really appreciate you taking the time to do that. Unfortunately though, it does not seem to be getting called when the dialog view dismisses. If you wouldn't mind checking to make sure it is in order, I would really aprpeciate it. Again thanks for your hard work on this!!!!

**Comment by ivanvorobei** [comment]
@sdevo619 I am tested and delegate call correctly. Describe your code or create simple project and send here.

![Screen Recording 2019-11-20 at 12 28 29](https://user-images.githubusercontent.com/10995774/69226685-98351300-0b91-11ea-90be-e916760e6ad1.gif)

**Comment by sdevo619** [comment]
It is working in the latest build. Thank you for all your hard work on this!!!! Have a great weekend!!!!
