### ISSUE TITLE
[Request] Can we also show allowed permissions in list?  not only not allowed

### ISSUE THREAD

**Issue by ppavel22** [ivanvorobei/SPPermissions#148]
First at all, thanks for your work. I have a small request. Can we also show allowed permissions in list?  not only not allowed. And could you please make titleLabel not on one line, since text is placed on 11 pro max, but not on X
![image](https://user-images.githubusercontent.com/32373042/69259455-f7f9e100-0bc6-11ea-8569-36ea520d2d77.png)
![image](https://user-images.githubusercontent.com/32373042/69259496-03e5a300-0bc7-11ea-89bd-4e9e4775fbf5.png)

**Comment by ivanvorobei** [comment]
@ppavel22 good day! 
By default all permissions which you pass show in list. Also allowed permission. Show your code for understand why showed only not allowed permissions.

About title - it navigation bar. Basic view. You can set small navigation.

**Comment by ppavel22** [comment]
oh, it was my mistake. sorry about that

**Comment by ppavel22** [comment]
navigationItem.title = titleText
        navigationItem.largeTitleDisplayMode = .automatic
        navigationController?.navigationBar.prefersLargeTitles = true its called after i setting 

        navigationItem.largeTitleDisplayMode = .never
        navigationController?.navigationBar.prefersLargeTitles = false

**Comment by ivanvorobei** [comment]
Yes, true. 
I will fix it in 1-2 hours. Please, wait.

**Comment by ivanvorobei** [comment]
@ppavel22 I add property `prefersLargeTitles` to `List` mode in new version. Please, update and check it.
