### ISSUE TITLE
Changing Base Color on v 5.1

### ISSUE THREAD

**Issue by jminutaglio** [ivanvorobei/SPPermissions#150]
Hello!

On the 4.x version I had used:
SPPermissionDialogColorSource

To alter the base color.  Does this function exist in 5.1?

**Comment by ivanvorobei** [comment]
Hi! 

Let me add this. I am complete today or tomorrow. When I publish new version I am write about it here.

**Comment by jminutaglio** [comment]
Awesome - thank you in advance!

**Comment by ivanvorobei** [comment]
I am publish new version `5.2.2` and update readme about new data source and delegate.
If big changes, need add some codes.

In data source implement this method:

```swift
func configure(_ cell: SPPermissionTableViewCell, for permission: SPPermission) -> SPPermissionTableViewCell {
    return cell
}
```

And configure cell:

```swift
// Colors
cell.iconView.color = .systemBlue
cell.button.allowedBackgroundColor = .systemBlue
cell.button.allowTitleColor = .systemBlue
```

Available more views for change colors, it for example. 
Don't forget about dark mode)
