### ISSUE TITLE
permissions parameter in didHide()

### ISSUE THREAD

**Issue by devjmitchell** [ivanvorobei/SPPermissions#154]
Hi,

Can you please add `permissions: [SPPermission]` as a parameter to the `didHide()` method?

When there's only one permission we ask for on a VC, it's easy to know which permission request the user dismissed and react accordingly... however, when there's multiple permissions we may be asking for and the user dismisses the request, it'd be nice to know which permission(s) were ignored.

Thanks!

**Comment by ivanvorobei** [comment]
Good idea! I am add it today)

**Comment by devjmitchell** [comment]
Great, thanks!

**Comment by ivanvorobei** [comment]
I am add it in `5.2.4`, please, update. I can't simple return array of permission, but I returned `ids` of permissions. Need init `SPPermission` with it `id`. You can see readme for more details.

 And thanks for cool idea!

**Comment by devjmitchell** [comment]
Cool - I'll take a look!
