### ISSUE TITLE
Did Hide Not being call in newest release

### ISSUE THREAD

**Issue by sdevo619** [ivanvorobei/SPPermissions#155]
Just updated to newest release a little while ago. Updated my code to use the new configure method, as it broke the previous updates code.  I do like the flexibility of the new method a lot though, so nice work again!!! Everything seems to be working great other than the didHide method is not being called anymore when I swipe the dialog controller off like I mentioned recently, a few weeks back, after the update. When you get a chance, can you please take a look and see if there is an issue there. Everything else is working great. Please keep up the great work!!!

**Comment by ivanvorobei** [comment]
Good day! 
I am run example project and all work correct. Delegate called, you can check it in example.

If you need help with usage, send here code which you use of archive simple project. I am try found mistake.

**Comment by ivanvorobei** [comment]
See this: 

![Screen Recording 2019-11-28 at 13 06 01](https://user-images.githubusercontent.com/10995774/69796963-fc825300-11df-11ea-851d-6856038f579a.gif)

**Comment by tewodroswondimu** [comment]
The delegate methods (didAllow, didDenied, deniedData)  are not being called for native permissions.

**Comment by ivanvorobei** [comment]
@tewodroswondimu you are right. I will fix it now and publish new version `5.2.8`. Please, update.
