### ISSUE TITLE
Problem with SPM

### ISSUE THREAD

**Issue by MoveUpwardsDev** [ivanvorobei/SPPermissions#156]
When using SPM to add the library, it crashes even if the xcconfig file has been correctly added and use to configure the project. Perhaps due to the fact that with SPM the complete SPPermissions library is added.

When using Pod with only the 2 modules i need, it works fine.

**Comment by ivanvorobei** [comment]
I will test it in 1-2 hours, thanks.

**Comment by ivanvorobei** [comment]
Yes, true. But I now know how pass flags in SPM. I don't understand why SPM ignore project flags. Need wait.

**Comment by MoveUpwardsDev** [comment]
No problem for the wait. i’ll use Pod. I’ll try to  find a way to tackle that problem with SPM. 

Great lib and more over clean code.

**Comment by huseyinbagana** [comment]
Is there any update for SPM ? It still crash.

**Comment by ivanvorobei** [comment]
@huseyinbagana for now I not found any solution. Recommend install via pods now.

**Comment by pkasson** [comment]
Same problem - @MoveUpwardsDev and @ivanvorobei - has anyone solved this ?

**Comment by pkasson** [comment]
Other option would be to just copy the project into another and use it directly ... SPM much cleaner than PODs

**Comment by ivanvorobei** [comment]
@pkasson please, read issue
For now no solution for SPM support, if you know how it fix - please, share with me

**Comment by furiosFast** [comment]
any news?

**Comment by ivanvorobei** [comment]
Now not work still, can't resolve it

**Comment by pkasson** [comment]
> @pkasson please, read issue
> For now no solution for SPM support, if you know how it fix - please, share with me

Maybe I overlooked it before - I see a Package.swift - isn't that for SPM ?

**Comment by pkasson** [comment]
So no one has gotten SPM to work with this ?  I have not setup a project yet with Package.swift, but it cant be that difficult, right ?   I can take a crack at it - if I get it working, will submit PR.

**Comment by pkasson** [comment]
Was able to add the SPM to XCode (12), using master branch.  It pulled it down and built without issue.

Looks to me like this is working !  If not, what issues are you having ?

**Comment by ivanvorobei** [comment]
@pkasson you simple install, now need set config for import only valid permissions. now it not work - that problem. You can't request permission

**Comment by pkasson** [comment]
Right - I see that it appears the xcconfig tags are not referenced in code - will research a bit - SPM better than pods !

**Comment by pkasson** [comment]
So, using a conditional check, from the xcconfig variables ... 

<#if SPPERMISSION_CAMERA>

fails in the app cant find that variable, but it is in the User-Defined block under build settings.

Is there any other project settings that need to support these xcconfig conditional variable ?  (sorry, new to some of this, but willing to help)

**Comment by ivanvorobei** [comment]
I tried different things. There is no way to configure SPM with flags yet

**Comment by pkasson** [comment]
yep - just cloned the project inside my app - looks great !  hopefully Apple will support this

**Comment by ivanvorobei** [comment]
Hi there! 

I doing new version `6.0` with support SPM and many other features. Soon I publish it.
