### ISSUE TITLE
Photo Library Permissions

### ISSUE THREAD

**Issue by jminutaglio** [ivanvorobei/SPPermissions#159]
Hey!

Noticed what I think is a bug in 5.2.6:
if the user has 'not allowed' photo library, and after that is selecting 'allow' in the SPPermissions dialog, there is no launch of the settings screen - the button graphically depresses, but the settings dialog does not appear.

-J

**Comment by jminutaglio** [comment]
actually it looks like its on any permission that is previously not allowed.

**Comment by ivanvorobei** [comment]
Good day! 

You override permission denied method?

**Comment by ivanvorobei** [comment]
I am tested in example project, alert show correctly.

**Comment by jminutaglio** [comment]
let me review the example project... and I will send some sample code... TY!

**Comment by jminutaglio** [comment]
ok - this was an error on my side in my 4.x->5.x migration.

I did not properly implement 
`func deniedData`

Thank you for your help and sorry for the false alarm.  I am going to reword the read me some, I see some English issues...
