### ISSUE TITLE
FaceId permissions

### ISSUE THREAD

**Issue by aididhaiqal** [ivanvorobei/SPPermissions#161]
Hi, is there any way to request permission for faceID?

**Comment by ivanvorobei** [comment]
Good day. Thanks for contact. I am try add it.

**Comment by dadou181295** [comment]
Hello sir. First Thanks for all your beautifull work ;D there is any update about the FaceID/TouchID permission ? I’m excited to use it and i’m sure there is a lot of people too :)

**Comment by furiosFast** [comment]
Hello,
I also join in to find out if there is any news about it. 
thank you

**Comment by ivanvorobei** [comment]
Hi, community! 

I check Face ID permission and can say - it not similar to location of camera. It other concept. 
Apple thave many way to evaluate policy and if declined FaceID, system try request passcode auth (for passcode no need permission).

Apple want use policy before it need, you need call simple func:
`context.evaluatePolicy()`
That include request and conformation process. You simple get result it in completion. 

No way request permission inly for FaceID and use it later.
