### ISSUE TITLE
How to change alert background color

### ISSUE THREAD

**Issue by Sargis** [ivanvorobei/SPPermissions#162]
I want change alert background color white to red (for example)
I am using swift with version 5

Thanks

**Comment by ivanvorobei** [comment]
Before presenting you create object of controller. 
Change color in property `view` if it controller.

**Comment by Sargis** [comment]
sorry but I want change alert dialog background color,

**Comment by ivanvorobei** [comment]
Maybe dialog? Alert it simple `UIAlertController`.

**Comment by Sargis** [comment]
right, dialod

**Comment by ivanvorobei** [comment]
Dialog it simple controller with table. See view hierarchy and change `view` color property.

**Comment by Sargis** [comment]
so I Need change tableview background Color, not Alert's superview Color:

there is my example

let controller = SPPermissions.dialog([ .notification, .camera])
controller.dialogView.backgroundColor = .red

but this is not work :(

**Comment by ivanvorobei** [comment]
Please, check code of this controller. 
`controller.dialogView.backgroundColor = .red` shouldn't work, because `viewDidLoad` call after it.

**Comment by Sargis** [comment]
so How Can I change dialogView Color?

ср, 25 дек. 2019 г. в 16:03, Ivan Vorobei <notifications@github.com>:

**Comment by ivanvorobei** [comment]
The controller does not currently support custom color out of the box. There are life hacks to help you do this. Call the color setting after `ViewDidLoad`, no matter what way.

**Comment by Sargis** [comment]
okay thanks, so I need change color from your framework code,
 I think it is bug :) 

Thank you

**Comment by ivanvorobei** [comment]
It not bug. Please, check lifecycle of controller. `init` call before `viewDidLoad`.
