### ISSUE TITLE
Doesn't work even with Cocoapods

### ISSUE THREAD

**Issue by incetro** [ivanvorobei/SPPermissions#166]
Hey. I'm trying to use your library using Cocoapods for installation. I've chosen 'SPPermissions/Location' and call it as `SPPermissions.native(.init(arrayLiteral: .locationAlwaysAndWhenInUse)).present(on: self)` and got this 'Fatal error: SPPermissions - Location Always not import. Probelm NOT with usage description key. I recomend to see installation guide: https://youtu.be/1kR5HGVhJfk. More details in Readme: https://github.com/ivanvorobei/SPPermissions'

**Comment by ivanvorobei** [comment]
Please, zip repo and send it here.

**Comment by incetro** [comment]
What repo is it about?

**Comment by ivanvorobei** [comment]
It simple Xcode project with your installing `SPPermissions`

**Comment by incetro** [comment]
That's my existing project which I can't send. I didn't create the new one as in your video example

**Comment by ivanvorobei** [comment]
If you not add any additional information or not send project, I can't say that happen. 

I am tested latest version - all ok. Check problem for your side.
