### ISSUE TITLE
Photo Library Not import issue

### ISSUE THREAD

**Issue by victormihaita** [ivanvorobei/SPPermissions#171]
I get this error when I check if photo library access is authorised:

```
Thread 1: Fatal error: SPPermissions - Photo Library not import. Probelm NOT with usage description key. I recomend to see installation guide: https://youtu.be/1kR5HGVhJfk. More details in Readme: https://github.com/ivanvorobei/SPPermissions
```

I have this in the pod file: 
```
pod 'SPPermissions/Camera'
pod 'SPPermissions/PhotoLibrary'
```

This is the code that is crashing:
```
let permissions: [SPPermission] = [.camera, .photoLibrary].filter { !$0.isAuthorized }
if permissions.isEmpty {
     //do something
}
```

If I use only the camera, it works
@ivanvorobei  Any suggestions?

**Comment by victormihaita** [comment]
I found the solution. I had to completely remove the pods, build without them, and them add them back. This seems to work. We don't actually need to use at all the `pod 'SPPermissions' `, so maybe explain it better in the documentation.

**Comment by ivanvorobei** [comment]
If you add `pod 'SPPermissions'` it nothing change. It simple bug installation. 
I hope all ok for now.

**Comment by victormihaita** [comment]
Everything works now. Is it possible to present the the alert without that shaking animation and remove the gesture to dismiss it? I would like to just disable all those fancy animations. is there a simple way to achieve that?
And great work!!!

**Comment by ivanvorobei** [comment]
@victormihaita for now no way do it.

**Comment by victormihaita** [comment]
Is this something that you may implement in the near future?

**Comment by ivanvorobei** [comment]
@victormihaita see problem, Apple not allow disable close alert for permissions. 
I can add remove animation, but gester really need for approve form Apple.

**Comment by victormihaita** [comment]
Okay. Then please just add the functionality to remove that animation to rotate the alert 🚨:) that would be really appreciated.

**Comment by ivanvorobei** [comment]
Please, create new issue for it. I will close when add it.

**Comment by ahmedsafadii** [comment]
SPPermissions - Photo Library not import 

have this issue also

**Comment by ivanvorobei** [comment]
@ahmedsafadii please, attach your podfile
