### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by sdevo619** [ivanvorobei/SPPermissions#173]
Just went to update Cooca Pods and ran into this error message. Any idea what is going on here??

[!] CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/2/e/e/SPPermissions/5.2.9/SPPermissions.podspec.json Response: Timeout was reached

Thank you, and keep up the great work!!!

**Comment by sdevo619** [comment]
Nevermind, now it is working!!!!! Have a great rest of your week!!!

**Comment by ivanvorobei** [comment]
Cocoa pods has some problems. Trying again and it work)
