### ISSUE TITLE
Always Get Fatal Error

### ISSUE THREAD

**Issue by kalathiyanilesh1** [ivanvorobei/SPPermissions#175]
getting error like Fatal error: SPPermission - Camera not import and app crashed.

i already added camera permission in info.plist file

**Comment by ivanvorobei** [comment]
Please, send me all error, which print in console.

**Comment by kalathiyanilesh1** [comment]
![Screenshot 2020-03-18 at 6 33 03 PM](https://user-images.githubusercontent.com/27014642/76963445-0bd00c80-6947-11ea-8dd8-7d4cbf4682a5.png)
![Screenshot 2020-03-18 at 6 33 12 PM](https://user-images.githubusercontent.com/27014642/76963458-1094c080-6947-11ea-8f09-d5e76d6fa135.png)
![Screenshot 2020-03-18 at 6 33 44 PM](https://user-images.githubusercontent.com/27014642/76963462-11c5ed80-6947-11ea-9f9e-aed48c2a5fd0.png)

**Comment by ivanvorobei** [comment]
@kalathiyanilesh1 please, for help you read that need
`Please, send me all error, which print in console.`

It all error in console.  Please, it need see.

Also please, send me Podfile. 

And please, confirm that you read readme before.

**Comment by kalathiyanilesh1** [comment]
@ivanvorobei here is my podfile

  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyJSON'
  pod 'SwiftMessages'
  pod 'Alamofire'
  pod 'SCPageControl'
  pod 'FloatingPanel'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SPPermissions', '4.1.4'
end


and console all error :

Fatal error: SPPermissions - Camera not import. Problem NOT with usage description key. I recomend to see installation guide: https://youtu.be/1kR5HGVhJfk. More details in Readme: https://github.com/ivanvorobei/SPPermissions: file /Users/imac/Documents/SourceCode/Boxly/boxly-app/BOXLY/Models/Libs/SPPermissions/Models/SPPermission.swift, line 125
2020-03-19 17:05:31.600680+0530 BOXLY[17560:184541] Fatal error: SPPermissions - Camera not import. Problem NOT with usage description key. I recomend to see installation guide: https://youtu.be/1kR5HGVhJfk. More details in Readme: https://github.com/ivanvorobei/SPPermissions: file /Users/imac/Documents/SourceCode/Boxly/boxly-app/BOXLY/Models/Libs/SPPermissions/Models/SPPermission.swift, line 125

**Comment by ivanvorobei** [comment]
Dear friend, please, pay more attention. See log

Fatal error: SPPermissions - Camera not import. Problem NOT with usage description key. I recomend to see installation guide: https://youtu.be/1kR5HGVhJfk. More details in Readme: https://github.com/ivanvorobei/SPPermissions

Problem NOT with description key. Also please, see how install SPPermission. You podfile incorrect.

**Comment by kalathiyanilesh1** [comment]
Hello @ivanvorobei ,

here is my ios code download it & let me know what was the issue.

https://we.tl/t-ijwOTe2g7f

**Comment by ivanvorobei** [comment]
@kalathiyanilesh1 please, read installation guide. 
not allowed install via
`pod 'SPPermissions`
