### ISSUE TITLE
how to use in cocoapods installed xcode project

### ISSUE THREAD

**Issue by cagricolak** [ivanvorobei/SPPermissions#177]
Hi Ivan,
My project needs to work with cocoapods, I manually copied your library to my project and got the error below.

> Fatal error: SPPermissions - Camera not import. Problem NOT with usage description key. I recomend to see installation guide: https://youtu.be/1kR5HGVhJfk.

I watched the your youtube video, and than copied the xcode's relase and debug configurations and followed your suggestion but got the same error again. either I have to disable cocoapods or your library but i have to use your library with my project, what is your suggestion? Thank you.

**Comment by ivanvorobei** [comment]
For now no way use custom config with Cocoapods. You should choose.

**Comment by cagricolak** [comment]
hi again, I deleted #if macros in SPPermission and ran it successfully,  how was it... 😎

**Comment by ivanvorobei** [comment]
If you add code manually, please check with permissions you integrate. You can get error with uploading and reject by apple.
