### ISSUE TITLE
Problem..

### ISSUE THREAD

**Issue by dadou181295** [ivanvorobei/SPPermissions#181]
Hello sir,  i'm trying to implement the notification permission and i got a crash  , the famous : 

"  Fatal error: SPPermissions - Notification not import. Problem NOT with usage description key. I recomend to see installation guide: https://youtu.be/1kR5HGVhJfk. More details in Readme: "

i saw the guide video in youtube but i cannot understand russian :(

i need to import all the source folder ? or should i need to import just the .config  permissionfile ?  where to put it ? please help :(

**Comment by dadou181295** [comment]
i import the SPPermision and added the notification permision Pod correctly but i dont understand..

**Comment by dadou181295** [comment]
Okay sir i drag all the 'source' file in my project but i got an error do you know why ?
![Capture d’écran 2020-04-17 à 15 55 19](https://user-images.githubusercontent.com/54495807/79571470-e78d5a00-80c3-11ea-8d9c-9868ad8f263e.png)

**Comment by ivanvorobei** [comment]
Please, show your podfile

**Comment by dadou181295** [comment]
i removed the source file sir and added it with swift package manager but i got the same error

**Comment by dadou181295** [comment]
can we talk in mail sir ?

**Comment by ivanvorobei** [comment]
If you use SPM or manually, need set config file. All process you can find in video.

**Comment by dadou181295** [comment]
for now i installled the  library with Swift package manager , added the  SPPermissionConfiguration.xcconfig only,  import SPPermision and added code to show notification . 

where is the problem ?

**Comment by dadou181295** [comment]
i did what you did in the video set target release and debug to SPPermisionConfiguration ..

**Comment by ivanvorobei** [comment]
Please, install via source code and set configuration

**Comment by dadou181295** [comment]
it's been 4 hours i'm trying sir.

added library with SPM added SPPermissionsConfiguration.xcconfig then go to PROJECT debug release -> target SPPpermision configuration ..

**Comment by dadou181295** [comment]
is the error related to input File lists in Build Phases ? 
tried to remove them still i got the same error..

**Comment by ivanvorobei** [comment]
@dadou181295 if you need my help - please, not ignore me. 

>  install via source code and set configuration

**Comment by dadou181295** [comment]
what do you mean via source code ?

**Comment by dadou181295** [comment]
download all source code folder and put it in my project  ?

**Comment by dadou181295** [comment]
lol now it's working just removed the pod and install it again ... D: 

Thanks you anyway sir god bless you
