### ISSUE TITLE
[Request] Siri Permission

### ISSUE THREAD

**Issue by joeljfischer** [ivanvorobei/SPPermissions#183]
Can we get something to request Siri authorization using `INPreferences`?

**Comment by ivanvorobei** [comment]
I fast check it and think I can add it to `SPPermissions` in next version

**Comment by ivanvorobei** [comment]
I think you need this?
`INPreferences.requestSiriAuthorization()`

**Comment by joeljfischer** [comment]
Yep, that’s the API. Though I just learned I don’t need the permission for custom intents oops🤦‍♂️

**Comment by ivanvorobei** [comment]
For intents yes, no need request it.
