### ISSUE TITLE
Localisation permission BUG?

### ISSUE THREAD

**Issue by dadou181295** [ivanvorobei/SPPermissions#185]
Sir the app get crashed everytime when im using trying to use the location permission showing you some screenshot tell me what do you think 
![Capture d’écran 2020-05-03 à 17 15 36](https://user-images.githubusercontent.com/54495807/80916510-d26e2780-8d61-11ea-8c74-3079ba43a283.png)
and in viewdidLoad adding the above funcs
![Capture d’écran 2020-05-03 à 17 16 00](https://user-images.githubusercontent.com/54495807/80916525-e2860700-8d61-11ea-8066-4d7486c49fc0.png)

**Comment by dadou181295** [comment]
same for the didAllow added code there and then calling to the function in view did load
by the way I did add the permission in info.plist ..

**Comment by dadou181295** [comment]
help me please sir :( am i doing something wrong ?:(

**Comment by dadou181295** [comment]
Okay i understand the locationWheninUse.isAuthorized is the only one working the other when in use and always doesnt work.. can you check sir ?

**Comment by ivanvorobei** [comment]
I can check, but please, clear write steps for reproduce and that result you wait

**Comment by dadou181295** [comment]
okay sorry for my bad english sir ^^

1. implemented the pod and the info.plist permission alwaysAndWhenInUse

2. import SPPPermission
3. implement the delegate and dataSource to my ViewController.
4. override the didDenied , didAllow , didHide.
5. in didDenied and didHide to check if there is permission i'm using :
 `   let state = SPPermission.locationAlwaysAndWhenInUse.isAuthorized`
6. in the didAllow just doing the code i want ( get the user's location and how it on map)
7. in the view did load i check again with 
  `   let state=SPPermission.locationAlwaysAndWhenInUse.isAuthorized`
if there is permission, if not show dialogue. 
--------
The problem is that when i click the ''allow' button to allow it with   dialogue it enter the Denied function

**Comment by ivanvorobei** [comment]
I tested now example app, delegate work correct.
Please, check example or pass more details.
