### ISSUE TITLE
Purpose of Checking SPPERMISSION_FLAGS?

### ISSUE THREAD

**Issue by muhasturk** [ivanvorobei/SPPermissions#188]
What is the purpose of checking every SPPERMISSION_FLAGS in xcconfig and throw fatalError if there is no flag defined. Just use it without compiler flags.

I already have my custom xcconfig file and I dont want to use any third party framework's xcconfig  file.

What should we do?

**Comment by muhasturk** [comment]
By the way I am using SPM for installation for SPPermissions. My workspace using own xcconfig file. So I could not select "SPPermissionsConfiguration.xcconfig" in project settings.

**Comment by muhasturk** [comment]
Integration with SPM is causing crash. Please do not check compiler flags.

**Comment by ivanvorobei** [comment]
Please, see this #156

**Comment by muhasturk** [comment]
I see that issue but there is no answer for my question. Is there any reason to check compiler flags? You can abort checking compiler flag for permission types.

**Comment by ivanvorobei** [comment]
You right, now no answer to your questions. It problem not solved now. 

Yes, need check compiler flags for permissions, it request by apple usage only required permissions in app. Without flags you catch full import of all permissions. And reject app after.
