### ISSUE TITLE
Cannot allow after denied it

### ISSUE THREAD

**Issue by flyinglionSJ** [ivanvorobei/SPPermissions#193]
Hi,

After I selected deny, I changed my mind and then I tapped on allow button and it did not work. Please help.

**Comment by ivanvorobei** [comment]
That behaviour you want see?

**Comment by pkasson** [comment]
A good experience would be to prompt the user, if they denied earlier, the option to enable it ... maybe not at every app launch, but periodically.

**Comment by ivanvorobei** [comment]
@pkasson project support alert about denied. About it you can read in readme.

**Comment by flyinglionSJ** [comment]
Hi,

Is it possible to allow user to allow it after deny?

Thanks,
T

**Comment by ivanvorobei** [comment]
@flyinglionSJ no, apple not show request again
