### ISSUE TITLE
SPPermission/Speech?

### ISSUE THREAD

**Issue by MHX792** [ivanvorobei/SPPermissions#204]
This is my podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!

target 'App' do
	
    pod 'SPPermission/Microphone'
    pod 'SPPermission/Speech'

end

```

It gives this error:

```
[!] CocoaPods could not find compatible versions for pod "SPPermission/Speech":
  In Podfile:
    SPPermission/Speech

None of your spec sources contain a spec satisfying the dependency: `SPPermission/Speech`.
```

If I comment out `pod 'SPPermission/Speech'`, it seems to install the *whole* framework: `Installing SPPermission 4.1`

**Comment by ivanvorobei** [comment]
Sorry, but `Speech` module really not available. Where you did find it?

**Comment by MHX792** [comment]
I didn't find it, but I was wondering why it was not available through cocoapods. That's why I was asking.

**Comment by ivanvorobei** [comment]
SPPermission is deprecated. Now available `SPPermissions`

**Comment by MHX792** [comment]
Unfortunately, it does not work with `pod 'SPPermissions/Speech'` either.

**Comment by ivanvorobei** [comment]
@MHX792 you install `SPPermission` lib, but create issue in `SPPermissions`. This not have speech module as I say before
