### ISSUE TITLE
Deprecation message

### ISSUE THREAD

**Issue by multinerd** [ivanvorobei/SPPermissions#206]
I am trying to figure out how you got the message `[!] SPPermission has been deprecated in favor of SPPermissions` to show up when i run `pod install`. Can you explain it?

**Comment by ivanvorobei** [comment]
You need set pod SPPermissions (last S)

**Comment by multinerd** [comment]
What I am asking is _how_ did you get that message to show up? How did you flag it so that cocoapods know it was deprecated?

I would think its something in the `podspec` file, but i didnt see anything that could be related.

**Comment by ivanvorobei** [comment]
https://blog.cocoapods.org/CocoaPods-0.32/

**Comment by multinerd** [comment]
Yea, i didnt see anything in your [podspec](https://github.com/ivanvorobei/SPPermissions/blob/master/SPPermissions.podspec).

Thanks for the link. I guess ill create test pods and play around with it.

**Comment by ivanvorobei** [comment]
Of course, because it pod spec not deprecated

**Comment by multinerd** [comment]
Oops, i meant to link to [this one](https://github.com/ivanvorobei/SPPermissions/blob/f5a47cbb95b48c65893187c2a392794b90542ea4/SPPermission.podspec).

That's the last commit with the `podspec` without the `s`.

Maybe you added the deprecated message and pushed to cocoapods but not to github? 
Thats the only thing that would make sense.

**Comment by ivanvorobei** [comment]
You again send me link on actual project) actual project not deprecated

**Comment by multinerd** [comment]
https://github.com/ivanvorobei/SPPermissions/blob/f5a47cbb95b48c65893187c2a392794b90542ea4/SPPermission.podspec

**Comment by multinerd** [comment]
My guess is that you didnt commit the old version's podspec with the deprecation flag to github, you only pushed to cocoapods and then pushed new version to github. thats why i couldnt see how you did it.

the blog post did help, not sure why my google-fu didnt bring that up.
Thanks.
