### ISSUE TITLE
Right way to comment out permissions?

### ISSUE THREAD

**Issue by MHX792** [ivanvorobei/SPPermissions#209]
What is the right way to comment out unneeded permissions?

*A:*
`SPPERMISSION_CAMERA            = //SPPERMISSION_CAMERA`

*B:*
`SPPERMISSION_CAMERA            //= SPPERMISSION_CAMERA`

*C:*
`//SPPERMISSION_CAMERA            = SPPERMISSION_CAMERA`

**Comment by ivanvorobei** [comment]
Sorry for so big delay. Please, use it:

```
// SPPERMISSION_CAMERA            = SPPERMISSION_CAMERA
```
