### ISSUE TITLE
Cocoapods installs everything

### ISSUE THREAD

**Issue by MHX792** [ivanvorobei/SPPermissions#210]
I added the following lines to the podfile:

```
pod 'SPPermissions/Microphone'
pod 'SPPermissions/SpeechRecognizer'
```

After running `pod install`, it outputs this:

```
Installing SPPermissions (5.4)
```

These files are then added to the `Pod` folder:
<img width="276" alt="Screenshot 2020-09-23 at 12 47 46" src="https://user-images.githubusercontent.com/12123471/94003054-07bff400-fd9b-11ea-9293-7651a84ad4f4.png">

Will the binary get rejected because of this?

**Comment by ivanvorobei** [comment]
No, file added but compile ignore unused files
