### ISSUE TITLE
Does SPPermissions support Arabic language?

### ISSUE THREAD

**Issue by Dubey-Shivani** [ivanvorobei/SPPermissions#214]
![Simulator Screen Shot - iPhone X - 2020-10-12 at 17 43 02](https://user-images.githubusercontent.com/44579259/95745299-74e7ea80-0cb2-11eb-8e96-8a3b77ead609.png)

I want to add support for Arabic language. But I am unable to find the icon and button placement when I change language to Arabic. Also the main titles or description are still left aligned, but they should be right aligned.

**Comment by ivanvorobei** [comment]
You right, `SPPermissions` now not support RTL. I have plans redo code to new major version, and add support many interesting things. Including RTL.

**Comment by Dubey-Shivani** [comment]
Can we do something quick for now or may I get code to contribute? I have managed to have their text localized. But for elements position it is not correct.
Swift manages its view orientation by itself.

**Comment by ivanvorobei** [comment]
You can do pull request

**Comment by ivanvorobei** [comment]
Announced `v6` version with support RTL.
