### ISSUE TITLE
How to change background blur view properties?

### ISSUE THREAD

**Issue by fattalgazi** [ivanvorobei/SPPermissions#218]
Hello there, I want to show black blurred view instead of white, how to do that?

Thank you.

![Simulator Screen Shot - iPhone 11 Pro - 2021-01-21 at 20 50 02](https://user-images.githubusercontent.com/3602109/105390669-56d34400-5c2a-11eb-9b80-52635898a21c.png)

**Comment by ivanvorobei** [comment]
I think you need to change `SPPermissionsGradeBlurView`, but views is private and you can't customise it. If it still valid for you, let me know for change protect level for you.
