### ISSUE TITLE
SPPermissionsDataSource

### ISSUE THREAD

**Issue by DiegoResnik** [ivanvorobei/SPPermissions#223]
SPPermissionsDataSource is not marked as @objc

**Comment by ivanvorobei** [comment]
Did you get any error with it?

**Comment by DiegoResnik** [comment]
without @objc it just not exposed to objectivec code. I've wrapped your code with a swift class and exposed it from there.

**Comment by ivanvorobei** [comment]
If need, I can fix it now. Let me know

**Comment by DiegoResnik** [comment]
As I said, I worked around this problem. I've noticed that other properties are with @objc so I've guess it's just a mistake...Maybe you want to fix this for others, or to maintain support for objectivec projects.

Anyway, Thank you for a wonderful component and for the support!
