### ISSUE TITLE
Does not build on Mac Catalyst since Xcode 12.5 (swift 5.4) update

### ISSUE THREAD

**Issue by zsbee** [ivanvorobei/SPPermissions#225]
![Screen Shot 2021-04-28 at 1 56 29 PM](https://user-images.githubusercontent.com/3268832/116399835-a2991900-a829-11eb-82ff-ab274d9b268a.png)

**Comment by zsbee** [comment]
instead of #if iOS we might need

#if !targetEnvironment(macCatalyst)

**Comment by ivanvorobei** [comment]
Released new version `5.5.1`, please update pods.
