### ISSUE TITLE
Bluetooth Permissions Required When Not Using BT (v5.5.5)

### ISSUE THREAD

**Issue by jminutaglio** [ivanvorobei/SPPermissions#226]
SPPermissions release 5.5.5

issue: Using SPPermissions, but not using BT generates errors upon app store submission:

Apple spits back invalid binary:
`ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSBluetoothPeripheralUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).`

And warning:
`ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSBluetoothAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).`

**Comment by ivanvorobei** [comment]
Did you install bluetooth or not?

**Comment by ivanvorobei** [comment]
Sorry, bug confirmed. Already published new version `5.5.7`

**Comment by jminutaglio** [comment]
TY Ivan!  Appreciate you!
