### ISSUE TITLE
SPM problem

### ISSUE THREAD

**Issue by furiosFast** [ivanvorobei/SPPermissions#230]
Hi,
when i add the SPPermissions library to my xcode (12.2) project i got this error:
![Schermata 2021-05-17 alle 14 12 13](https://user-images.githubusercontent.com/38165952/118486500-fc4e7e00-b719-11eb-8ae4-e76a661eb2be.png)

**Comment by ivanvorobei** [comment]
Which version did you try install?

**Comment by furiosFast** [comment]
I've tried with 6.0.0 and 6.0.2

**Comment by ivanvorobei** [comment]
Sorry, I see. Can you update Xcode? It solve problem. 
SPM user tools 5.4 version.

**Comment by furiosFast** [comment]
ok
