### ISSUE TITLE
I can't check permission

### ISSUE THREAD

**Issue by kidanh** [ivanvorobei/SPPermissions#232]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/48889319/118821285-49c91780-b8e1-11eb-9ccc-ec4f8d2ea76f.png">

**Comment by jminutaglio** [comment]
Same bug for me also.

**Comment by jminutaglio** [comment]
this is impacting the configuration of permissions also:

<img width="691" alt="Screen Shot 2021-05-19 at 10 40 49 AM" src="https://user-images.githubusercontent.com/49879291/118832630-c979c680-b88e-11eb-835f-99bc077f593c.png">

**Comment by ivanvorobei** [comment]
How did install `SPPermissions`?

**Comment by jminutaglio** [comment]
Installed via CocoaPods

**Comment by ivanvorobei** [comment]
I see. 1 minute please for release new version.

**Comment by jminutaglio** [comment]
Thank you!!!!  :)

**Comment by ivanvorobei** [comment]
Fixed in new version `6.0.8`. Please, use `pod update`.
