### ISSUE TITLE
Buttons Not Showing in >6.0.8

### ISSUE THREAD

**Issue by jminutaglio** [ivanvorobei/SPPermissions#235]
**Describe the bug**
Buttons are not showing in >`6.0.8`.  When you click them they show...  They're transparent or white on white...

Initial view:
<img width="390" alt="Screen Shot 2021-05-20 at 11 18 42 AM" src="https://user-images.githubusercontent.com/49879291/119005617-994d2900-b95d-11eb-9a1e-cb43619b4139.png">

But can be clicked, and then show:
<img width="390" alt="Screen Shot 2021-05-20 at 11 20 28 AM" src="https://user-images.githubusercontent.com/49879291/119005658-a0743700-b95d-11eb-934d-3490fccc58e6.png">

This was introduced in `6.0.9`.  `6.0.8 `did not exhibit this behavior.  Validated the bug/behavior is in `6.0.10` also

**Smartphone (please complete the following information):**
 - iOS Version 14.4
 - `SPPermissions` version 6.0.10
 - Installed via Cocoapods

**Comment by ivanvorobei** [comment]
Fixed in `6.1.1`.

**Comment by jminutaglio** [comment]
ty!

**Comment by jminutaglio** [comment]
Confirmed resolved!  ty again!
