### ISSUE TITLE
Build not passing on CI using SPM

### ISSUE THREAD

**Issue by victormihaita** [ivanvorobei/SPPermissions#236]
**Describe the bug**
When I build locally I can test the app on the simulator but when I run the app on CI is failing with this error: 

```
xcodebuild: error: Could not resolve package dependencies:
  because SPPermissions >=5.5.1 contains incompatible tools version and root depends on SPPermissions 6.1.1, version solving failed.
```

**Screenshots**

**Smartphone (please complete the following information):**
 - iOS Version 13
 - `SPPermissions` version 6.1.1
 - Installed via SPM

**Comment by ivanvorobei** [comment]
Hi there! 
Which Xcode version are you use?

**Comment by victormihaita** [comment]
Is fixed now. I had to use the latest stack on Bitrise CI (XCode 12.5.x on MacOS 11.2).
