### ISSUE TITLE
Type 'SPPermissions.Permission' has no member 'camera' so on

### ISSUE THREAD

**Issue by PacoPacoPakitor** [ivanvorobei/SPPermissions#242]
- iOS Version 14.5.1
 - SPPermissions version 6.0.9
 - Installed via Cocoapods

i copy code from the example, but i has met this issue from my side, can u help me to check why have this happen?

![image](https://user-images.githubusercontent.com/23376484/121861095-bb02bb80-cd23-11eb-84b7-df6498f79e69.png)

**Comment by ivanvorobei** [comment]
Good day! 
Provide please full file which you use and podspec too.

**Comment by PacoPacoPakitor** [comment]
> Good day!
> Provide please full file which you use and podspec too.
Hi, sorry for the i missing the pods 
here is which i installed from cocoapods 
  pod 'SPPermissions'
here is which file i import
import SPPermissions
the above it's all i used in the code

**Comment by ivanvorobei** [comment]
Yes, you missing other modules. [Here](https://github.com/ivanvorobei/SPPermissions#cocoapods) full info. Please, close issue if not actual.

**Comment by PacoPacoPakitor** [comment]
thank you so much.
