### ISSUE TITLE
Configurable title for .denied

### ISSUE THREAD

**Issue by jminutaglio** [ivanvorobei/SPPermissions#243]
**Is your feature request related to a problem? Please describe.**
Changes in Apple App Store review guidelines (5.1.1) result in a different use case for SPPermissions - ie: as a pre-flight for the native prompts.  In this use case it would make sense for a `denied` status button title.

**Describe the solution you'd like**
An additional status for denied would help usability.

```
    func configure(_ cell: SPPermissionsTableViewCell, for permission: SPPermissions.Permission) {
        // Titles
        
        cell.permissionButton.allowTitle = "Continue"
        cell.permissionButton.allowedTitle = "Allowed"

```        

something like `cell.permissionButton.deniedTitle`

Would clarify the preflight UX:
<img width="344" alt="Screen Shot 2021-06-14 at 11 10 23 AM" src="https://user-images.githubusercontent.com/49879291/121919036-9cd99300-cd04-11eb-83b1-51d83d829505.png">

in this screen (from:  v.6.4.11):
- Camera & Photo Library are `.notDetermined`
- Location is `.denied`
- Media Library is `.authorized`

A separate title for `.denied` would clarify state in a pre-flight use case.

Thanks in advance for any consideration.

**Comment by ivanvorobei** [comment]
Thanks for your propose. Tonight going to do it and publish new version.

**Comment by jminutaglio** [comment]
thank you.

add'l:
`    func deniedAlertTexts(for permission: SPPermissions.Permission) -> SPPermissionDeniedAlertTexts? {
`

Should only run when the button was already in `.denied` state, not when clicked in `.notDetermined` state...

in other words:
- if the permission is in `.notDetermined` -> permission is denied, the button text changes to `cell.permissionButton.deniedTitle`
- if the permission is in `.denied` -> `deniedAlertTexts` runs.

This allows for greater compliance with the suggestion:

> Don't ask the user to change their mind if they deny permission.


thx.

**Comment by ivanvorobei** [comment]
Fully agree with you, should change it before. So wait next update.

**Comment by ivanvorobei** [comment]
Fixed both in `6.5.0` version. Thanks!

**Comment by jminutaglio** [comment]
ty!

`func deniedAlertTexts(for permission: SPPermissions.Permission) -> SPPermissionDeniedAlertTexts? {
`

Still seems to run on the first click (changing status from `.notDetermined` to `.denied`).  IE: when the user initially denies the permission they are prompted immediately again...

**Comment by ivanvorobei** [comment]
Do you sure about new version installed?

**Comment by ivanvorobei** [comment]
UPD: catch problem, only in dialog.

**Comment by ivanvorobei** [comment]
Fixed in `6.5.1`.

**Comment by jminutaglio** [comment]
confirmed fixed!  Thank you so much for these changes!  I appreciate you!!

**Comment by 8secz-johndpope** [comment]
Great work - I found a glitch with my ux
I present 2 items [notifications, tracking]

https://gist.github.com/8secz-johndpope/37ef042d445a8a8045fed0e8411c6398

I deny tracking 
I enable notification

I end up with both buttons configured (allowed / denied)- but no way to dismiss them.

**Comment by 8secz-johndpope** [comment]
![IMG_4508](https://user-images.githubusercontent.com/50567111/123724720-27f38500-d8d0-11eb-836d-74c5b93d0ce4.PNG)
