### ISSUE TITLE
Swipe Close changes for App Review Guidelines

### ISSUE THREAD

**Issue by jminutaglio** [ivanvorobei/SPPermissions#244]
**Is your feature request related to a problem? Please describe.**
As Apple's guideline is now to not allow the user to abandon the permission request flow, per:

> A message appears before the permission request, and the user can close the message and delay the permission request with the “X” button. The user should always proceed to the permission request after the message.

**Describe the solution you'd like**
It would make sense to disable the swipe dismiss function as well as the "X" button.  Ex:
```
// Work for any style
controller.showCloseButton = true

```

Could be augmented to include:
`controller.allowSwipeDismiss = true`

Or similar...

TY for any consideration.

**Comment by ivanvorobei** [comment]
Added in `6.5.0` version. Thanks!
