### ISSUE TITLE
Type 'SPPermissions.Permission' has no member 'camera'

### ISSUE THREAD

**Issue by VladK9** [ivanvorobei/SPPermissions#247]
**Screenshots**
<img width="789" alt="Bug" src="https://user-images.githubusercontent.com/50109143/123462271-89330400-d603-11eb-8846-084402184158.png">

**Smartphone (please complete the following information):**
 - iOS Version [14.6]
 - `SPPermissions` version [6.5.4]
 - Installed via [ Manually]

**Comment by ivanvorobei** [comment]
Did you add compile flags?

**Comment by VladK9** [comment]
Yes, even with older versions

**Comment by VladK9** [comment]
**Compile flags** are those in the .plist?

**Comment by ivanvorobei** [comment]
No, its other, Its objc flags in Xcode, did you add it?

**Comment by VladK9** [comment]
I need to add them in Xcode section **Swift compiler - Custom flags**?

**Comment by ivanvorobei** [comment]
yes, right
