### ISSUE TITLE
Why is called didHidePermissions function after press on "cancel" of denied alert?

### ISSUE THREAD

**Issue by furiosFast** [ivanvorobei/SPPermissions#250]
Hi,
i must do some action after the Sppermission controller is closed, for do that i used the didHidePermissions function, but now if a user touch on denied button and after touch the cancel button of the alert, the didHidePermissions func is called. why?
thank you

**Comment by furiosFast** [comment]
another thing: why the "denied" button in Sppermission controller no present che custom color setted: 
`cell.permissionButton.allowedBackgroundColor = UIColor(named: "AccentColor")!`

**Comment by furiosFast** [comment]
Another things: how to auto dismiss the controller when all permission are requested from the user (status different from notDetermined)

**Comment by ivanvorobei** [comment]
About call `didHidePermissions `, really bug for dialog. Also I added property `dismissReason` for controllers, you can set it to dismiss if all permissions determinated.

New version released, please update for have it.

**Comment by furiosFast** [comment]
thank you
