### ISSUE TITLE
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by Oggerschummer** [ivanvorobei/SPPermissions#252]
**Describe the bug**
After upgrading to Xcode 13 B3 I see the error in the build:
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.
This was not the case in earlier versions of Xcode (e.g. 13B1).
**To Reproduce**
Added SPPermissions as SwiftPackage, start build

**Expected behavior**
Should build without issue.

**Smartphone (please complete the following information):**
 - iOS Version: 15B3
 - `SPPermissions` version: Latest
 - Installed via SPM

**Additional context**
Its an app without any extensions thus I do not get why this is thrown. I´m stuck.

**Comment by Oggerschummer** [comment]
Tried with a different project / workspace. Same result, does not build anymore.

**Comment by ivanvorobei** [comment]
Yes, have problem in beta. Searching solution

**Comment by Oggerschummer** [comment]
Did cross-check with B2, here the build works. So maybe they broke something in B3,

**Comment by ivanvorobei** [comment]
Xcode disable using shared for class `UIApplication`, that reason. I think I need do some changes in code and remove all using shared. Main idea have controller for present. I will check it and return with new version. I let you know here today-tomorrow.

**Comment by Oggerschummer** [comment]
How about marking your function explicitly unavailable for application extensions using 
`@available(iOSApplicationExtension,unavailable)`
Seems that Xcode is making the mistake thinking SPPermissions is an application extension.
This could be a potential workaround...

**Comment by ivanvorobei** [comment]
Did it, thanks! New version is `6.6.0` should work fine with Xcode 13.3. Issue closed. Let me know if you have any problem.

**Comment by Oggerschummer** [comment]
Works perfectly fine, compile error is gone.Thanks!Am 22.07.2021 21:51 schrieb Ivan Vorobei ***@***.***>:
Did it, thanks! New version is 6.6.0 should work fine with Xcode 13.3. Issue closed. Let me know if you have any problem.
