### ISSUE TITLE
SPM: 'shared' is unavailable in application extensions for iOS

### ISSUE THREAD

**Issue by JMCPH** [ivanvorobei/SPPermissions#253]
**Describe the bug**
When building with Xcode 13 beta 3 I get the following error:

`'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`

**To Reproduce**
Install through SPM.

**Expected behavior**

**Screenshots**

**Smartphone**
 - iOS Version [14.7.1]
 - `SPPermissions` version [6.5.6]
 - Installed via [SPM]

**Additional context**

**Comment by ivanvorobei** [comment]
Closed because you use old version. More info here:
https://github.com/ivanvorobei/SPPermissions/issues/252
