### ISSUE TITLE
SPPermission Type

### ISSUE THREAD

**Issue by SouthernGirlWhoCode** [ivanvorobei/SPPermissions#254]
When creating permission for camera, notification and others, I'm getting this error "Type 'Array<SPPermissions.Permission>.ArrayLiteralElement' (aka 'SPPermissions.Permission') has no member 'camera'"

<img width="1067" alt="Screenshot 2021-08-02 at 13 33 47" src="https://user-images.githubusercontent.com/70700757/127862550-420901a4-a75d-48b4-b207-9d1b011bd8e8.png">

I copied all of the subfolders from Source folder into my project.

**Comment by ivanvorobei** [comment]
Please, provide details about install way and imports.

**Comment by SouthernGirlWhoCode** [comment]
> Please, provide details about install way and imports.

See edited: I copied all of the subfolders from Source folder into my project.

**Comment by ivanvorobei** [comment]
Did you add compile flags?

**Comment by SouthernGirlWhoCode** [comment]
> Did you add compile flags?

Yes I did as instructed - https://github.com/ivanvorobei/SPPermissions/blob/main/CONTRIBUTING.md#active-compilation-conditions

**Comment by ivanvorobei** [comment]
Share please how you added this flags

**Comment by SouthernGirlWhoCode** [comment]
> Share please how you added this flags

<img width="830" alt="Screenshot 2021-08-02 at 19 02 14" src="https://user-images.githubusercontent.com/70700757/127904515-113dccd2-1e26-4558-8189-541b0b4c15e6.png">

**Comment by ivanvorobei** [comment]
Please, do this. I made empty project and tested - all should be good.

<img width="1031" alt="Screenshot 2021-08-02 at 21 07 58" src="https://user-images.githubusercontent.com/10995774/127905051-b15ab913-54a7-47ae-8aeb-71a16b95c153.png">
