### ISSUE TITLE
i want to hide dialogue in multiple permission

### ISSUE THREAD

**Issue by anil72178** [ivanvorobei/SPPermissions#255]
How to hide dialogue automatically when user allow or denied all permission..

like i have 3 permission [.photoLibrary, .notification,.tracking]

in this i have only photo library permission is necessary while other 2 is optional so if user denied other 2 permission dialogue is not hide automatically...

so how to hide dialogue when user action on all permission ?

**Comment by ivanvorobei** [comment]
You should implement delegate, catch event about allowed of denied permission. 
When need dismiss, simple call for controller `dismiss` method like for usual controller. 

Please, don't use bug label in future. It's not bug.
