### ISSUE TITLE
'Permission' is not a member type of enum 'SPPermissions.SPPermissions'

### ISSUE THREAD

**Issue by kerepuki** [ivanvorobei/SPPermissions#257]
Hi,

When trying to implement this library I get the error when adding
`var availablePermissions: [SPPermissions.Permission] = [.notification, .locationWhenInUse, .locationAlways, .bluetooth]`
`'Permission' is not a member type of enum 'SPPermissions.SPPermissions'`

iOS 14.5, Swift 5. SPPermissions 5.5.8

Thanks

**Comment by ivanvorobei** [comment]
Please, update to latest version. Already available `6.6.3`.
