### ISSUE TITLE
The close button in the upper right corner is in the wrong position

### ISSUE THREAD

**Issue by chenjc0317** [ivanvorobei/SPPermissions#258]
**Describe the bug**
The close button in the upper right corner is in the wrong position

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - iOS Version：14.5
 - Framework Version：6.6.3
 - Installed via：Cocoapods

**Additional context**
![Simulator Screen Shot - iPhone 12 - 2021-08-11 at 14 21 42](https://user-images.githubusercontent.com/47734570/128979924-5327adc2-419c-40c4-8168-db564c3349de.png)

**Comment by chenjc0317** [comment]
![Simulator Screen Shot - iPhone 12 - 2021-08-11 at 14 21 42](https://user-images.githubusercontent.com/47734570/128979842-bbc91086-a85f-4527-94b1-fb2b8f7b2005.png)

**Comment by ivanvorobei** [comment]
Thanks, going to fix it today.

**Comment by ivanvorobei** [comment]
Fixed in `6.6.4` version. Please, update.
