### ISSUE TITLE
Setting bounceAnimationEnabled = false on iOS 12 causes items in dialog mode not showing

### ISSUE THREAD

**Issue by Weberlolz** [ivanvorobei/SPPermissions#262]
**Describe the bug**
Setting bounceAnimationEnabled = false on iOS 12 causes items in dialog mode not showing.

**To Reproduce**
let controller = SPPermissions.dialog(permissions)
controller.bounceAnimationEnabled = false

**Expected behavior**
Should show up all permission items.

**Screenshots**
![iOS12_simulator](https://user-images.githubusercontent.com/7581657/135382541-eb908eb4-678e-423a-a5ec-7f333f821979.png)

**Smartphone (please complete the following information):**
 - iOS 12
 - Framework Version 6.7.0
 - Installed via Cocoapods

**Comment by ivanvorobei** [comment]
Sorry for big delay. Fixed in `6.8.1` version.
