### ISSUE TITLE
Permissions Icons do not show on iPhone X, Xr.

### ISSUE THREAD

**Issue by jminutaglio** [ivanvorobei/SPPermissions#263]
**Describe the bug**
Permission icons are not showing on certain iPhone screen sizes, ex: iPhone X, Xr.

**To Reproduce**
- Standard build on different phone simulators will show issue.

**Screenshots**
<img width="510" alt="Screen Shot 2021-10-04 at 9 39 11 PM" src="https://user-images.githubusercontent.com/49879291/135947166-07e068c9-e3f1-406f-9b1f-bb36c81a017b.png">
iPhone Xr on the left, 13ProMax on right, same code.

**Smartphone (please complete the following information):**
 - iOS Version [e.g. 14.5.1]: 15.0
 - Framework Version [e.g. 3.0.8] : 6.7.1
 - Installed via [e.g. SPM, Cocoapods, Manually]: Cocoapods

**Additional context**
TY in advance for taking a look at this!

**Comment by ivanvorobei** [comment]
Hello! I checked it, all ok for me. Can you check it again pleas
<img width="125" alt="Screenshot 2021-10-05 at 10 31 11" src="https://user-images.githubusercontent.com/10995774/135981927-888baf23-11e5-487a-a945-c578088ea1db.png">
<img width="125" alt="Screenshot 2021-10-05 at 10 31 04" src="https://user-images.githubusercontent.com/10995774/135981946-627054b7-8b24-4efb-8132-d4a23c5cf7da.png">
e?

**Comment by jminutaglio** [comment]
@ivanvorobei - ok let me take another look and better document the recreation steps/code.  TY!

**Comment by jminutaglio** [comment]
@ivanvorobei - after clean build folder, etc & recompile all is fine.  My apologies, this appears to have been on my end.
