### ISSUE TITLE
Bug with dynamic typing

### ISSUE THREAD

**Issue by DavidDHansson** [ivanvorobei/SPPermissions#267]
When a user has enabled "Larger Accessibility Sizes" under "Accessibility" -> "Display & Text Size" -> "Larger Text" and also turned up the font-size, the permission view from the library is unusable.

To reproduce
- Go to system settings and go to "Accessibility" -> "Display & Text Size" -> "Larger Text".
- Enable "Larger Accessibility Sizes"
- Turn the font-size to the max!
- Go to an app that uses SPPermissions and have a permission view appear

A solution would be to ignore the systems font-size and only use predefined font-sizes?

Screenshots:
![Simulator Screen Shot - iPhone 8 - 2021-10-22 at 10 42 30](https://user-images.githubusercontent.com/55251118/138424675-b7083cc3-a657-4c74-91cc-925508cdca9c.png)
![Simulator Screen Shot - iPhone 8 - 2021-10-22 at 10 50 54](https://user-images.githubusercontent.com/55251118/138424680-473ec3dd-2b8d-4fda-b5d9-c352f3e40708.png)
![Simulator Screen Shot - iPhone 8 - 2021-10-22 at 10 51 22](https://user-images.githubusercontent.com/55251118/138424685-0f25c0ce-dd72-4c7b-8eb6-939734bb53a8.png)

**Comment by ivanvorobei** [comment]
Sorry for delay, fixed in `6.8.0`.
