### ISSUE TITLE
Optionally bundle images

### ISSUE THREAD

**Issue by marko-cancar** [ivanvorobei/SPPermissions#271]
Currently Assets.car weight ~2MB. That is more than 50% of my overall app size (Yes I want my app to be as light as possible 😄) and I am not using any of its assets (I use SF symbols instead, which I suggest as well btw).

I would like that Image assets are bundled into SPPermissions_SPPermissions.bundle only if at least one of images is being used in the app.

**Comment by ivanvorobei** [comment]
Sorry, I don't understand which file is around 2mb.

**Comment by marko-cancar** [comment]
Assets.car is a "compiled" version of Assets.xcassets which is packed along with the app or framework.

**Comment by ivanvorobei** [comment]
@marko-cancar sorry, `Assets.xcassets` is vector images pack. Size is 214kb.

<img width="350" alt="Screenshot 2021-11-18 at 12 30 58" src="https://user-images.githubusercontent.com/10995774/142388830-8e27c077-c200-4e01-9afc-4388604f9084.png">
