### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by aleejin** [ivanvorobei/SPPermissions#276]
Our online application crashed, but we didn't confirm the cause of the problem

![E5549139-393F-4241-980D-A183A61B2F40](https://user-images.githubusercontent.com/11660922/148864613-d603f985-1d1f-4960-b6d8-45a1a08b375f.png)

**Comment by ivanvorobei** [comment]
Please, use issue template and fill all details with code usage.
Try call this in empty clean project also.
