### ISSUE TITLE
Permission Health can't be present with custom interface

### ISSUE THREAD

**Issue by yuchenz27** [ivanvorobei/SPPermissions#281]
I want to ask permission for Health. Here is my code
```
let controller = SPPermissions.list([.camera, .microphone, .health])
controller.present(on: self)
```

As a result, the health option was not presented in the pop-up list and I got this message in console:
```
SPPermissions: Permission Health can't be present with custom interface. Use `SPPermissions.Permission.NAME.request()` with requerid parametrs. Permission Health will be filtered.
```
Could someone tell me how to properly ask Health permission? Thank you very much.

**Comment by ivanvorobei** [comment]
Hey. Health permission has a lot of type. Better to use native way.
